#!/usr/bin/env python3
"""Traceability gate.

Fails (exit 1) when:
  * an acceptance criterion in spec.md has no scenario or test covering it, or
  * a scenario/test references an AC that does not exist in spec.md (orphan).

Usage:
  python tools/check_traceability.py            # print the matrix, exit 1 on gaps
  python tools/check_traceability.py --write    # also write docs/traceability.md
"""
from __future__ import annotations

import re
import sys
from collections import defaultdict
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
SPEC_DIR = ROOT / "specs" / "001-appointment-booking"

spec_text = (SPEC_DIR / "spec.md").read_text()
criteria = dict(re.findall(r"- \*\*(AC-\d{3})\*\* \(([^)]*)\)", spec_text))

coverage: dict[str, list[str]] = defaultdict(list)
for sc in yaml.safe_load((SPEC_DIR / "acceptance.yaml").read_text())["scenarios"]:
    coverage[sc["id"]].append(f"acceptance.yaml: {sc['title']}")

for test_file in sorted((ROOT / "tests").glob("test_*.py")):
    for ac, fn in re.findall(r'@pytest\.mark\.ac\("(AC-\d{3})"\)\s*\ndef (\w+)', test_file.read_text()):
        coverage[ac].append(f"{test_file.name}::{fn}")

uncovered = [ac for ac in criteria if not coverage.get(ac)]
orphans = sorted(set(coverage) - set(criteria))

lines = ["| AC | Traces to | Covered by |", "|---|---|---|"]
for ac, refs in criteria.items():
    by = "<br>".join(coverage.get(ac, [])) or "❌ **NOT COVERED**"
    lines.append(f"| {ac} | {refs} | {by} |")
matrix = "\n".join(lines)

print(matrix)
print(f"\n{len(criteria)} criteria · {len(criteria) - len(uncovered)} covered · "
      f"{len(uncovered)} uncovered · {len(orphans)} orphan references")

if "--write" in sys.argv:
    out = ROOT / "docs" / "traceability.md"
    out.parent.mkdir(exist_ok=True)
    out.write_text("# Traceability matrix (generated)\n\n"
                   "Generated by `tools/check_traceability.py --write`. Do not edit by hand.\n\n"
                   + matrix + "\n")
    print(f"wrote {out.relative_to(ROOT)}")

if uncovered or orphans:
    if uncovered:
        print(f"FAIL: uncovered criteria: {', '.join(uncovered)}")
    if orphans:
        print(f"FAIL: references to criteria not in spec.md: {', '.join(orphans)}")
    sys.exit(1)
print("PASS: every acceptance criterion is covered")
